# Generated by Django 3.2.8 on 2021-10-18 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20210307_2100'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_type',
            field=models.CharField(blank=True, choices=[('', 'select profile type'), ('Staff', 'Staff'), ('System Admin', 'System Admin'), ('Valuer', 'Valuer')], max_length=100, null=True),
        ),
    ]
